NB_TURN=50
NB_GAMES=1
training:
	python client.py zi05ue57 training $(NB_TURN) Jacky

Jacky:	
	python client.py zi05ue57 arena $(NB_GAMES) Jacky
Wilson:
	python client.py c6dm7bo9 arena $(NB_GAMES) Wilson




